### PR TITLE
calling the udocker script with python2

### PR DESCRIPTION
**Pull request by samthiriot**
fix https://github.com/openmole/openmole/issues/288

### CODE REVIEW

**Comment by romainreuillon** [comment]
I have to try that on the grid before merging it. The grid runs really old linux distributions. I hope it will work otherwise a test would be required before to check if pyhton or python2 should be called.

**Comment by romainreuillon** [comment]
It seems to be working even on old distrib.

**Comment by jopasserat** [comment]
That means we need to have python2 on the user's machine for this to work..
And I'm pretty sure some distros come with python3 by default now.

Summoning a python export here.
If there's any chance you can enlighten us with your python lore @ghisvail?

**Comment by romainreuillon** [comment]
I was always the case, udocker only works on python2. From there 2 ways to go:
 * find a way to craft an portable executable embedding the python interpreter
 * code our own user mode container lib in scala

**Comment by jopasserat** [comment]
Sure but as it is it could lead to a cryptic error complaining that `python2: no such file or directory`. Quite unsettling if you're not using python in your docker image :grinning: 

I think udocker will have to be rewritten to support python3. I've naively tried a `2to3` but it still screams at me so won't go further down that road.

Option 1 will very likely rely on PRoot, and you know.. There's this thing to generate standalone binaries from python scripts https://pyinstaller.readthedocs.io/en/stable/usage.html but I think it should be done upstream in udocker, will report it there as well.

Option 2 is doable, we have quite some work done already with the inhouse layers download and @vincenthage 's OCI images loader: https://github.com/vincenthage/proot-oci-loader

**Pull request merged**
