### PR TITLE
[DOC] fix: Edit the doc

### PR DESCRIPTION
**Pull request by jopasserat**
Please check the edits for correctness :)

### CODE REVIEW

**Comment by jopasserat** [comment]
Just edited files starting with G-H

**Comment by jopasserat** [comment]
Add edits for files starting with M-P

**Comment by jopasserat** [comment]
Layout is not quite as expected...
It seems Scalatex and I don't agree on how to define sections and their depth...

**Comment by romainreuillon** [comment]
Meaning, that it can be merged?

**Comment by jopasserat** [comment]
Almost... I'm finishing the last file in the T-W range.

**Comment by jopasserat** [comment]
Just need to fix the merge conflicts and see if it compiles fine.

**Pull request merged**
