### PR TITLE
Sensitivity analysis: Morris

### PR DESCRIPTION
**Pull request by samthiriot**
Hello,

here is a proposal for the implementation of the Morris sensitivity analysis developed during the coding camp. 

Another pull request follows on the market for verification and examples.

Comments and patches welcomed !

S.

### CODE REVIEW

**Comment by samthiriot** [comment]
I wonder if the package named should not be "methods" rather than "sampling". Up to you.

**Comment by romainreuillon** [comment]
Indeed, I agree. I think it would be better labelled as a method.

**Comment by samthiriot** [comment]
@romainreuillon done, thanks

**Comment by romainreuillon** [comment]
I think the println should be replaced by logging. I'll refactor that after the merge.

**Pull request merged**
