### PR TITLE
#42 Fix change of linked input file mode

### PR DESCRIPTION
**Pull request by schuhschuh**
Tested and confirmed.

### CODE REVIEW

**Comment by schuhschuh** [comment]
Hold on, I have to go back and trace again... the input files remain unchanged, but some intermediate files still have executable bit set.

**Comment by schuhschuh** [comment]
This PR is now ready to be merged. It fixes the issue #42.

**Comment by romainreuillon** [comment]
Great! 

Could you just reenable the authorizeLS, so in case the operation is not "delete" the file get the permission preserved? Also a test of existence should be added in the finally operation of authoriseLS.

**Comment by schuhschuh** [comment]
I don't see the need for a local function definition when it is only invoked once. But if you prefer having it, fine.

**Comment by romainreuillon** [comment]
It is just to make the intent explicit.

**Comment by schuhschuh** [comment]
Which a comment would do much better than an unknown abbreviation such as "LS"... :P

No complaints, though, I will add it back. You code is overall pretty well written.

**Comment by romainreuillon** [comment]
It is a question of style but I always prefer improving code clarity against commenting it, since comments might get out of sync.

**Comment by schuhschuh** [comment]
Is it correct that the purpose of ```authorizeLS``` is to ```authorizeListFiles``` ? Shall I rename ?

**Comment by romainreuillon** [comment]
Totally agree for the new name, the clearer the better.

**Pull request merged**
